# Generated by Django 5.2 on 2025-04-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('variável', 'Variável')], default='variável', max_length=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Investimentos', 'Investimentos'), ('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Presentes', 'Presentes'), ('Cuidados Pessoais', 'Cuidados Pessoais'), ('Lazer', 'Lazer'), ('Custos Fixos', 'Custos Fixos')], max_length=30),
        ),
    ]
