# Generated by Django 5.2 on 2025-04-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='tipo',
        ),
    ]
